/*
MongoDB Atlas Administration API

The MongoDB Atlas Administration API allows developers to manage all components in MongoDB Atlas. To learn more, review the [Administration API overview](https://www.mongodb.com/docs/atlas/api/atlas-admin-api/). This OpenAPI specification covers all of the collections with the exception of Alerts, Alert Configurations, and Events. Refer to the [legacy documentation](https://www.mongodb.com/docs/atlas/reference/api-resources/) for the specifications of these resources.

API version: 2.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package api

import (
	"encoding/json"
)

// DataLakeOnlineArchiveStoreAllOf struct for DataLakeOnlineArchiveStoreAllOf
type DataLakeOnlineArchiveStoreAllOf struct {
	// ID of the Cluster the Online Archive belongs to.
	ClusterId *string `json:"clusterId,omitempty"`
	// Name of the Cluster the Online Archive belongs to.
	ClusterName *string `json:"clusterName,omitempty"`
	// ID of the Project the Online Archive belongs to.
	ProjectId *string `json:"projectId,omitempty"`
}

// NewDataLakeOnlineArchiveStoreAllOf instantiates a new DataLakeOnlineArchiveStoreAllOf object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewDataLakeOnlineArchiveStoreAllOf() *DataLakeOnlineArchiveStoreAllOf {
	this := DataLakeOnlineArchiveStoreAllOf{}
	return &this
}

// NewDataLakeOnlineArchiveStoreAllOfWithDefaults instantiates a new DataLakeOnlineArchiveStoreAllOf object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewDataLakeOnlineArchiveStoreAllOfWithDefaults() *DataLakeOnlineArchiveStoreAllOf {
	this := DataLakeOnlineArchiveStoreAllOf{}
	return &this
}

// GetClusterId returns the ClusterId field value if set, zero value otherwise.
func (o *DataLakeOnlineArchiveStoreAllOf) GetClusterId() string {
	if o == nil || o.ClusterId == nil {
		var ret string
		return ret
	}
	return *o.ClusterId
}

// GetClusterIdOk returns a tuple with the ClusterId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DataLakeOnlineArchiveStoreAllOf) GetClusterIdOk() (*string, bool) {
	if o == nil || o.ClusterId == nil {
		return nil, false
	}
	return o.ClusterId, true
}

// HasClusterId returns a boolean if a field has been set.
func (o *DataLakeOnlineArchiveStoreAllOf) HasClusterId() bool {
	if o != nil && o.ClusterId != nil {
		return true
	}

	return false
}

// SetClusterId gets a reference to the given string and assigns it to the ClusterId field.
func (o *DataLakeOnlineArchiveStoreAllOf) SetClusterId(v string) {
	o.ClusterId = &v
}

// GetClusterName returns the ClusterName field value if set, zero value otherwise.
func (o *DataLakeOnlineArchiveStoreAllOf) GetClusterName() string {
	if o == nil || o.ClusterName == nil {
		var ret string
		return ret
	}
	return *o.ClusterName
}

// GetClusterNameOk returns a tuple with the ClusterName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DataLakeOnlineArchiveStoreAllOf) GetClusterNameOk() (*string, bool) {
	if o == nil || o.ClusterName == nil {
		return nil, false
	}
	return o.ClusterName, true
}

// HasClusterName returns a boolean if a field has been set.
func (o *DataLakeOnlineArchiveStoreAllOf) HasClusterName() bool {
	if o != nil && o.ClusterName != nil {
		return true
	}

	return false
}

// SetClusterName gets a reference to the given string and assigns it to the ClusterName field.
func (o *DataLakeOnlineArchiveStoreAllOf) SetClusterName(v string) {
	o.ClusterName = &v
}

// GetProjectId returns the ProjectId field value if set, zero value otherwise.
func (o *DataLakeOnlineArchiveStoreAllOf) GetProjectId() string {
	if o == nil || o.ProjectId == nil {
		var ret string
		return ret
	}
	return *o.ProjectId
}

// GetProjectIdOk returns a tuple with the ProjectId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DataLakeOnlineArchiveStoreAllOf) GetProjectIdOk() (*string, bool) {
	if o == nil || o.ProjectId == nil {
		return nil, false
	}
	return o.ProjectId, true
}

// HasProjectId returns a boolean if a field has been set.
func (o *DataLakeOnlineArchiveStoreAllOf) HasProjectId() bool {
	if o != nil && o.ProjectId != nil {
		return true
	}

	return false
}

// SetProjectId gets a reference to the given string and assigns it to the ProjectId field.
func (o *DataLakeOnlineArchiveStoreAllOf) SetProjectId(v string) {
	o.ProjectId = &v
}

func (o DataLakeOnlineArchiveStoreAllOf) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.ClusterId != nil {
		toSerialize["clusterId"] = o.ClusterId
	}
	if o.ClusterName != nil {
		toSerialize["clusterName"] = o.ClusterName
	}
	if o.ProjectId != nil {
		toSerialize["projectId"] = o.ProjectId
	}
	return json.Marshal(toSerialize)
}

type NullableDataLakeOnlineArchiveStoreAllOf struct {
	value *DataLakeOnlineArchiveStoreAllOf
	isSet bool
}

func (v NullableDataLakeOnlineArchiveStoreAllOf) Get() *DataLakeOnlineArchiveStoreAllOf {
	return v.value
}

func (v *NullableDataLakeOnlineArchiveStoreAllOf) Set(val *DataLakeOnlineArchiveStoreAllOf) {
	v.value = val
	v.isSet = true
}

func (v NullableDataLakeOnlineArchiveStoreAllOf) IsSet() bool {
	return v.isSet
}

func (v *NullableDataLakeOnlineArchiveStoreAllOf) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDataLakeOnlineArchiveStoreAllOf(val *DataLakeOnlineArchiveStoreAllOf) *NullableDataLakeOnlineArchiveStoreAllOf {
	return &NullableDataLakeOnlineArchiveStoreAllOf{value: val, isSet: true}
}

func (v NullableDataLakeOnlineArchiveStoreAllOf) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDataLakeOnlineArchiveStoreAllOf) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


