language: go

go:
  - 1.12.x
  - 1.13.x
  - 1.14.x
  - tip

matrix:
  fast_finish: true
  allow_failures:
    - go: tip
  include:
  - name: "Code Lint"
    before_install: make tools
    script: make lint

script: make test
