/*
MongoDB Atlas Administration API

The MongoDB Atlas Administration API allows developers to manage all components in MongoDB Atlas. To learn more, review the [Administration API overview](https://www.mongodb.com/docs/atlas/api/atlas-admin-api/). This OpenAPI specification covers all of the collections with the exception of Alerts, Alert Configurations, and Events. Refer to the [legacy documentation](https://www.mongodb.com/docs/atlas/reference/api-resources/) for the specifications of these resources.

API version: 2.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package v1

import (
	"encoding/json"
)

// PartitionFieldView Metadata to partition this online archive.
type PartitionFieldView struct {
	// Human-readable label that identifies the parameter that MongoDB Cloud uses to partition data. To specify a nested parameter, use the dot notation.
	FieldName string `json:"fieldName"`
	// Data type of the parameter that that MongoDB Cloud uses to partition data. Partition parameters of type [UUID](http://bsonspec.org/spec.html) must be of binary subtype 4. MongoDB Cloud skips partition parameters of type UUID with subtype 3.
	FieldType *string `json:"fieldType,omitempty"`
	// Sequence in which MongoDB Cloud slices the collection data to create partitions. The resource expresses this sequence starting with zero. The value of the **criteria.dateField** parameter defaults as the first item in the partition sequence.
	Order int32 `json:"order"`
}

// NewPartitionFieldView instantiates a new PartitionFieldView object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPartitionFieldView() *PartitionFieldView {
	this := PartitionFieldView{}
	var order int32 = 0
	this.Order = order
	return &this
}

// NewPartitionFieldViewWithDefaults instantiates a new PartitionFieldView object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPartitionFieldViewWithDefaults() *PartitionFieldView {
	this := PartitionFieldView{}
	var order int32 = 0
	this.Order = order
	return &this
}

// GetFieldName returns the FieldName field value
func (o *PartitionFieldView) GetFieldName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.FieldName
}

// GetFieldNameOk returns a tuple with the FieldName field value
// and a boolean to check if the value has been set.
func (o *PartitionFieldView) GetFieldNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.FieldName, true
}

// SetFieldName sets field value
func (o *PartitionFieldView) SetFieldName(v string) {
	o.FieldName = v
}

// GetFieldType returns the FieldType field value if set, zero value otherwise.
func (o *PartitionFieldView) GetFieldType() string {
	if o == nil || o.FieldType == nil {
		var ret string
		return ret
	}
	return *o.FieldType
}

// GetFieldTypeOk returns a tuple with the FieldType field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PartitionFieldView) GetFieldTypeOk() (*string, bool) {
	if o == nil || o.FieldType == nil {
		return nil, false
	}
	return o.FieldType, true
}

// HasFieldType returns a boolean if a field has been set.
func (o *PartitionFieldView) HasFieldType() bool {
	if o != nil && o.FieldType != nil {
		return true
	}

	return false
}

// SetFieldType gets a reference to the given string and assigns it to the FieldType field.
func (o *PartitionFieldView) SetFieldType(v string) {
	o.FieldType = &v
}

// GetOrder returns the Order field value
func (o *PartitionFieldView) GetOrder() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Order
}

// GetOrderOk returns a tuple with the Order field value
// and a boolean to check if the value has been set.
func (o *PartitionFieldView) GetOrderOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Order, true
}

// SetOrder sets field value
func (o *PartitionFieldView) SetOrder(v int32) {
	o.Order = v
}

func (o PartitionFieldView) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["fieldName"] = o.FieldName
	}
	if o.FieldType != nil {
		toSerialize["fieldType"] = o.FieldType
	}
	if true {
		toSerialize["order"] = o.Order
	}
	return json.Marshal(toSerialize)
}

type NullablePartitionFieldView struct {
	value *PartitionFieldView
	isSet bool
}

func (v NullablePartitionFieldView) Get() *PartitionFieldView {
	return v.value
}

func (v *NullablePartitionFieldView) Set(val *PartitionFieldView) {
	v.value = val
	v.isSet = true
}

func (v NullablePartitionFieldView) IsSet() bool {
	return v.isSet
}

func (v *NullablePartitionFieldView) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePartitionFieldView(val *PartitionFieldView) *NullablePartitionFieldView {
	return &NullablePartitionFieldView{value: val, isSet: true}
}

func (v NullablePartitionFieldView) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePartitionFieldView) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


