generatorName: go
gitRepoId: go-client-mongodb-atlas
gitUserId: mongodb
vanityURL: go.mongodb.org/atlas
templateDir: "./config/go-templates"
generateInterfaces: true
enumClassPrefix: true
structPrefix: true
useOneOfDiscriminatorLookup: true
files:
  atlas_client.mustache:
    templateType: SupportingFiles
    destinationFilename: atlas_client.go
  api_store.mustache:
    templateType: API
    destinationFilename: atlas_stores.go
