/*
MongoDB Atlas Administration API

The MongoDB Atlas Administration API allows developers to manage all components in MongoDB Atlas. To learn more, review the [Administration API overview](https://www.mongodb.com/docs/atlas/api/atlas-admin-api/). This OpenAPI specification covers all of the collections with the exception of Alerts, Alert Configurations, and Events. Refer to the [legacy documentation](https://www.mongodb.com/docs/atlas/reference/api-resources/) for the specifications of these resources.

API version: 2.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package v1alpha

import (
	"encoding/json"
)

// ClusterDescriptionProcessArgs struct for ClusterDescriptionProcessArgs
type ClusterDescriptionProcessArgs struct {
	// [Default level of acknowledgment requested from MongoDB for read operations](https://docs.mongodb.com/manual/reference/read-concern/) set for this cluster.  MongoDB 4.4 clusters default to `available`. MongoDB 5.0 and later clusters default to `local`.
	DefaultReadConcern *string `json:"defaultReadConcern,omitempty"`
	// [Default level of acknowledgment requested from MongoDB for write operations](https://docs.mongodb.com/manual/reference/write-concern/) set for this cluster.  MongoDB 4.4 clusters default to `1`. MongoDB 5.0 and later clusters default to `majority`.
	DefaultWriteConcern *string `json:"defaultWriteConcern,omitempty"`
	// Flag that indicates whether you can insert or update documents where all indexed entries don't exceed 1024 bytes. If you set this to false, [mongod](https://docs.mongodb.com/upcoming/reference/program/mongod/#mongodb-binary-bin.mongod) writes documents that exceed this limit but doesn't index them.
	FailIndexKeyTooLong *bool `json:"failIndexKeyTooLong,omitempty"`
	// Flag that indicates whether the cluster allows execution of operations that perform server-side executions of JavaScript.
	JavascriptEnabled *bool `json:"javascriptEnabled,omitempty"`
	// Minimum Transport Layer Security (TLS) version that the cluster accepts for incoming connections. Clusters using TLS 1.0 or 1.1 should consider setting TLS 1.2 as the minimum TLS protocol version.
	MinimumEnabledTlsProtocol *string `json:"minimumEnabledTlsProtocol,omitempty"`
	// Flag that indicates whether the cluster disables executing any query that requires a collection scan to return results.
	NoTableScan *bool `json:"noTableScan,omitempty"`
	// Minimum retention window for cluster's oplog expressed in hours. A value of null indicates that the cluster uses the default minimum oplog window that MongoDB Cloud calculates.
	OplogMinRetentionHours NullableFloat64 `json:"oplogMinRetentionHours,omitempty"`
	// Storage limit of cluster's oplog expressed in megabytes. A value of null indicates that the cluster uses the default oplog size that MongoDB Cloud calculates.
	OplogSizeMB NullableInt32 `json:"oplogSizeMB,omitempty"`
	// Interval in seconds at which the mongosqld process re-samples data to create its relational schema.
	SampleRefreshIntervalBIConnector *int32 `json:"sampleRefreshIntervalBIConnector,omitempty"`
	// Number of documents per database to sample when gathering schema information.
	SampleSizeBIConnector *int32 `json:"sampleSizeBIConnector,omitempty"`
}

// NewClusterDescriptionProcessArgs instantiates a new ClusterDescriptionProcessArgs object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewClusterDescriptionProcessArgs() *ClusterDescriptionProcessArgs {
	this := ClusterDescriptionProcessArgs{}
	var defaultReadConcern string = "available"
	this.DefaultReadConcern = &defaultReadConcern
	var defaultWriteConcern string = "1"
	this.DefaultWriteConcern = &defaultWriteConcern
	var failIndexKeyTooLong bool = true
	this.FailIndexKeyTooLong = &failIndexKeyTooLong
	var javascriptEnabled bool = true
	this.JavascriptEnabled = &javascriptEnabled
	var noTableScan bool = false
	this.NoTableScan = &noTableScan
	var sampleRefreshIntervalBIConnector int32 = 0
	this.SampleRefreshIntervalBIConnector = &sampleRefreshIntervalBIConnector
	var sampleSizeBIConnector int32 = 1000
	this.SampleSizeBIConnector = &sampleSizeBIConnector
	return &this
}

// NewClusterDescriptionProcessArgsWithDefaults instantiates a new ClusterDescriptionProcessArgs object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewClusterDescriptionProcessArgsWithDefaults() *ClusterDescriptionProcessArgs {
	this := ClusterDescriptionProcessArgs{}
	var defaultReadConcern string = "available"
	this.DefaultReadConcern = &defaultReadConcern
	var defaultWriteConcern string = "1"
	this.DefaultWriteConcern = &defaultWriteConcern
	var failIndexKeyTooLong bool = true
	this.FailIndexKeyTooLong = &failIndexKeyTooLong
	var javascriptEnabled bool = true
	this.JavascriptEnabled = &javascriptEnabled
	var noTableScan bool = false
	this.NoTableScan = &noTableScan
	var sampleRefreshIntervalBIConnector int32 = 0
	this.SampleRefreshIntervalBIConnector = &sampleRefreshIntervalBIConnector
	var sampleSizeBIConnector int32 = 1000
	this.SampleSizeBIConnector = &sampleSizeBIConnector
	return &this
}

// GetDefaultReadConcern returns the DefaultReadConcern field value if set, zero value otherwise.
func (o *ClusterDescriptionProcessArgs) GetDefaultReadConcern() string {
	if o == nil || o.DefaultReadConcern == nil {
		var ret string
		return ret
	}
	return *o.DefaultReadConcern
}

// GetDefaultReadConcernOk returns a tuple with the DefaultReadConcern field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ClusterDescriptionProcessArgs) GetDefaultReadConcernOk() (*string, bool) {
	if o == nil || o.DefaultReadConcern == nil {
		return nil, false
	}
	return o.DefaultReadConcern, true
}

// HasDefaultReadConcern returns a boolean if a field has been set.
func (o *ClusterDescriptionProcessArgs) HasDefaultReadConcern() bool {
	if o != nil && o.DefaultReadConcern != nil {
		return true
	}

	return false
}

// SetDefaultReadConcern gets a reference to the given string and assigns it to the DefaultReadConcern field.
func (o *ClusterDescriptionProcessArgs) SetDefaultReadConcern(v string) {
	o.DefaultReadConcern = &v
}

// GetDefaultWriteConcern returns the DefaultWriteConcern field value if set, zero value otherwise.
func (o *ClusterDescriptionProcessArgs) GetDefaultWriteConcern() string {
	if o == nil || o.DefaultWriteConcern == nil {
		var ret string
		return ret
	}
	return *o.DefaultWriteConcern
}

// GetDefaultWriteConcernOk returns a tuple with the DefaultWriteConcern field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ClusterDescriptionProcessArgs) GetDefaultWriteConcernOk() (*string, bool) {
	if o == nil || o.DefaultWriteConcern == nil {
		return nil, false
	}
	return o.DefaultWriteConcern, true
}

// HasDefaultWriteConcern returns a boolean if a field has been set.
func (o *ClusterDescriptionProcessArgs) HasDefaultWriteConcern() bool {
	if o != nil && o.DefaultWriteConcern != nil {
		return true
	}

	return false
}

// SetDefaultWriteConcern gets a reference to the given string and assigns it to the DefaultWriteConcern field.
func (o *ClusterDescriptionProcessArgs) SetDefaultWriteConcern(v string) {
	o.DefaultWriteConcern = &v
}

// GetFailIndexKeyTooLong returns the FailIndexKeyTooLong field value if set, zero value otherwise.
func (o *ClusterDescriptionProcessArgs) GetFailIndexKeyTooLong() bool {
	if o == nil || o.FailIndexKeyTooLong == nil {
		var ret bool
		return ret
	}
	return *o.FailIndexKeyTooLong
}

// GetFailIndexKeyTooLongOk returns a tuple with the FailIndexKeyTooLong field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ClusterDescriptionProcessArgs) GetFailIndexKeyTooLongOk() (*bool, bool) {
	if o == nil || o.FailIndexKeyTooLong == nil {
		return nil, false
	}
	return o.FailIndexKeyTooLong, true
}

// HasFailIndexKeyTooLong returns a boolean if a field has been set.
func (o *ClusterDescriptionProcessArgs) HasFailIndexKeyTooLong() bool {
	if o != nil && o.FailIndexKeyTooLong != nil {
		return true
	}

	return false
}

// SetFailIndexKeyTooLong gets a reference to the given bool and assigns it to the FailIndexKeyTooLong field.
func (o *ClusterDescriptionProcessArgs) SetFailIndexKeyTooLong(v bool) {
	o.FailIndexKeyTooLong = &v
}

// GetJavascriptEnabled returns the JavascriptEnabled field value if set, zero value otherwise.
func (o *ClusterDescriptionProcessArgs) GetJavascriptEnabled() bool {
	if o == nil || o.JavascriptEnabled == nil {
		var ret bool
		return ret
	}
	return *o.JavascriptEnabled
}

// GetJavascriptEnabledOk returns a tuple with the JavascriptEnabled field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ClusterDescriptionProcessArgs) GetJavascriptEnabledOk() (*bool, bool) {
	if o == nil || o.JavascriptEnabled == nil {
		return nil, false
	}
	return o.JavascriptEnabled, true
}

// HasJavascriptEnabled returns a boolean if a field has been set.
func (o *ClusterDescriptionProcessArgs) HasJavascriptEnabled() bool {
	if o != nil && o.JavascriptEnabled != nil {
		return true
	}

	return false
}

// SetJavascriptEnabled gets a reference to the given bool and assigns it to the JavascriptEnabled field.
func (o *ClusterDescriptionProcessArgs) SetJavascriptEnabled(v bool) {
	o.JavascriptEnabled = &v
}

// GetMinimumEnabledTlsProtocol returns the MinimumEnabledTlsProtocol field value if set, zero value otherwise.
func (o *ClusterDescriptionProcessArgs) GetMinimumEnabledTlsProtocol() string {
	if o == nil || o.MinimumEnabledTlsProtocol == nil {
		var ret string
		return ret
	}
	return *o.MinimumEnabledTlsProtocol
}

// GetMinimumEnabledTlsProtocolOk returns a tuple with the MinimumEnabledTlsProtocol field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ClusterDescriptionProcessArgs) GetMinimumEnabledTlsProtocolOk() (*string, bool) {
	if o == nil || o.MinimumEnabledTlsProtocol == nil {
		return nil, false
	}
	return o.MinimumEnabledTlsProtocol, true
}

// HasMinimumEnabledTlsProtocol returns a boolean if a field has been set.
func (o *ClusterDescriptionProcessArgs) HasMinimumEnabledTlsProtocol() bool {
	if o != nil && o.MinimumEnabledTlsProtocol != nil {
		return true
	}

	return false
}

// SetMinimumEnabledTlsProtocol gets a reference to the given string and assigns it to the MinimumEnabledTlsProtocol field.
func (o *ClusterDescriptionProcessArgs) SetMinimumEnabledTlsProtocol(v string) {
	o.MinimumEnabledTlsProtocol = &v
}

// GetNoTableScan returns the NoTableScan field value if set, zero value otherwise.
func (o *ClusterDescriptionProcessArgs) GetNoTableScan() bool {
	if o == nil || o.NoTableScan == nil {
		var ret bool
		return ret
	}
	return *o.NoTableScan
}

// GetNoTableScanOk returns a tuple with the NoTableScan field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ClusterDescriptionProcessArgs) GetNoTableScanOk() (*bool, bool) {
	if o == nil || o.NoTableScan == nil {
		return nil, false
	}
	return o.NoTableScan, true
}

// HasNoTableScan returns a boolean if a field has been set.
func (o *ClusterDescriptionProcessArgs) HasNoTableScan() bool {
	if o != nil && o.NoTableScan != nil {
		return true
	}

	return false
}

// SetNoTableScan gets a reference to the given bool and assigns it to the NoTableScan field.
func (o *ClusterDescriptionProcessArgs) SetNoTableScan(v bool) {
	o.NoTableScan = &v
}

// GetOplogMinRetentionHours returns the OplogMinRetentionHours field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ClusterDescriptionProcessArgs) GetOplogMinRetentionHours() float64 {
	if o == nil || o.OplogMinRetentionHours.Get() == nil {
		var ret float64
		return ret
	}
	return *o.OplogMinRetentionHours.Get()
}

// GetOplogMinRetentionHoursOk returns a tuple with the OplogMinRetentionHours field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ClusterDescriptionProcessArgs) GetOplogMinRetentionHoursOk() (*float64, bool) {
	if o == nil {
		return nil, false
	}
	return o.OplogMinRetentionHours.Get(), o.OplogMinRetentionHours.IsSet()
}

// HasOplogMinRetentionHours returns a boolean if a field has been set.
func (o *ClusterDescriptionProcessArgs) HasOplogMinRetentionHours() bool {
	if o != nil && o.OplogMinRetentionHours.IsSet() {
		return true
	}

	return false
}

// SetOplogMinRetentionHours gets a reference to the given NullableFloat64 and assigns it to the OplogMinRetentionHours field.
func (o *ClusterDescriptionProcessArgs) SetOplogMinRetentionHours(v float64) {
	o.OplogMinRetentionHours.Set(&v)
}
// SetOplogMinRetentionHoursNil sets the value for OplogMinRetentionHours to be an explicit nil
func (o *ClusterDescriptionProcessArgs) SetOplogMinRetentionHoursNil() {
	o.OplogMinRetentionHours.Set(nil)
}

// UnsetOplogMinRetentionHours ensures that no value is present for OplogMinRetentionHours, not even an explicit nil
func (o *ClusterDescriptionProcessArgs) UnsetOplogMinRetentionHours() {
	o.OplogMinRetentionHours.Unset()
}

// GetOplogSizeMB returns the OplogSizeMB field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ClusterDescriptionProcessArgs) GetOplogSizeMB() int32 {
	if o == nil || o.OplogSizeMB.Get() == nil {
		var ret int32
		return ret
	}
	return *o.OplogSizeMB.Get()
}

// GetOplogSizeMBOk returns a tuple with the OplogSizeMB field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ClusterDescriptionProcessArgs) GetOplogSizeMBOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return o.OplogSizeMB.Get(), o.OplogSizeMB.IsSet()
}

// HasOplogSizeMB returns a boolean if a field has been set.
func (o *ClusterDescriptionProcessArgs) HasOplogSizeMB() bool {
	if o != nil && o.OplogSizeMB.IsSet() {
		return true
	}

	return false
}

// SetOplogSizeMB gets a reference to the given NullableInt32 and assigns it to the OplogSizeMB field.
func (o *ClusterDescriptionProcessArgs) SetOplogSizeMB(v int32) {
	o.OplogSizeMB.Set(&v)
}
// SetOplogSizeMBNil sets the value for OplogSizeMB to be an explicit nil
func (o *ClusterDescriptionProcessArgs) SetOplogSizeMBNil() {
	o.OplogSizeMB.Set(nil)
}

// UnsetOplogSizeMB ensures that no value is present for OplogSizeMB, not even an explicit nil
func (o *ClusterDescriptionProcessArgs) UnsetOplogSizeMB() {
	o.OplogSizeMB.Unset()
}

// GetSampleRefreshIntervalBIConnector returns the SampleRefreshIntervalBIConnector field value if set, zero value otherwise.
func (o *ClusterDescriptionProcessArgs) GetSampleRefreshIntervalBIConnector() int32 {
	if o == nil || o.SampleRefreshIntervalBIConnector == nil {
		var ret int32
		return ret
	}
	return *o.SampleRefreshIntervalBIConnector
}

// GetSampleRefreshIntervalBIConnectorOk returns a tuple with the SampleRefreshIntervalBIConnector field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ClusterDescriptionProcessArgs) GetSampleRefreshIntervalBIConnectorOk() (*int32, bool) {
	if o == nil || o.SampleRefreshIntervalBIConnector == nil {
		return nil, false
	}
	return o.SampleRefreshIntervalBIConnector, true
}

// HasSampleRefreshIntervalBIConnector returns a boolean if a field has been set.
func (o *ClusterDescriptionProcessArgs) HasSampleRefreshIntervalBIConnector() bool {
	if o != nil && o.SampleRefreshIntervalBIConnector != nil {
		return true
	}

	return false
}

// SetSampleRefreshIntervalBIConnector gets a reference to the given int32 and assigns it to the SampleRefreshIntervalBIConnector field.
func (o *ClusterDescriptionProcessArgs) SetSampleRefreshIntervalBIConnector(v int32) {
	o.SampleRefreshIntervalBIConnector = &v
}

// GetSampleSizeBIConnector returns the SampleSizeBIConnector field value if set, zero value otherwise.
func (o *ClusterDescriptionProcessArgs) GetSampleSizeBIConnector() int32 {
	if o == nil || o.SampleSizeBIConnector == nil {
		var ret int32
		return ret
	}
	return *o.SampleSizeBIConnector
}

// GetSampleSizeBIConnectorOk returns a tuple with the SampleSizeBIConnector field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ClusterDescriptionProcessArgs) GetSampleSizeBIConnectorOk() (*int32, bool) {
	if o == nil || o.SampleSizeBIConnector == nil {
		return nil, false
	}
	return o.SampleSizeBIConnector, true
}

// HasSampleSizeBIConnector returns a boolean if a field has been set.
func (o *ClusterDescriptionProcessArgs) HasSampleSizeBIConnector() bool {
	if o != nil && o.SampleSizeBIConnector != nil {
		return true
	}

	return false
}

// SetSampleSizeBIConnector gets a reference to the given int32 and assigns it to the SampleSizeBIConnector field.
func (o *ClusterDescriptionProcessArgs) SetSampleSizeBIConnector(v int32) {
	o.SampleSizeBIConnector = &v
}

func (o ClusterDescriptionProcessArgs) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.DefaultReadConcern != nil {
		toSerialize["defaultReadConcern"] = o.DefaultReadConcern
	}
	if o.DefaultWriteConcern != nil {
		toSerialize["defaultWriteConcern"] = o.DefaultWriteConcern
	}
	if o.FailIndexKeyTooLong != nil {
		toSerialize["failIndexKeyTooLong"] = o.FailIndexKeyTooLong
	}
	if o.JavascriptEnabled != nil {
		toSerialize["javascriptEnabled"] = o.JavascriptEnabled
	}
	if o.MinimumEnabledTlsProtocol != nil {
		toSerialize["minimumEnabledTlsProtocol"] = o.MinimumEnabledTlsProtocol
	}
	if o.NoTableScan != nil {
		toSerialize["noTableScan"] = o.NoTableScan
	}
	if o.OplogMinRetentionHours.IsSet() {
		toSerialize["oplogMinRetentionHours"] = o.OplogMinRetentionHours.Get()
	}
	if o.OplogSizeMB.IsSet() {
		toSerialize["oplogSizeMB"] = o.OplogSizeMB.Get()
	}
	if o.SampleRefreshIntervalBIConnector != nil {
		toSerialize["sampleRefreshIntervalBIConnector"] = o.SampleRefreshIntervalBIConnector
	}
	if o.SampleSizeBIConnector != nil {
		toSerialize["sampleSizeBIConnector"] = o.SampleSizeBIConnector
	}
	return json.Marshal(toSerialize)
}

type NullableClusterDescriptionProcessArgs struct {
	value *ClusterDescriptionProcessArgs
	isSet bool
}

func (v NullableClusterDescriptionProcessArgs) Get() *ClusterDescriptionProcessArgs {
	return v.value
}

func (v *NullableClusterDescriptionProcessArgs) Set(val *ClusterDescriptionProcessArgs) {
	v.value = val
	v.isSet = true
}

func (v NullableClusterDescriptionProcessArgs) IsSet() bool {
	return v.isSet
}

func (v *NullableClusterDescriptionProcessArgs) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableClusterDescriptionProcessArgs(val *ClusterDescriptionProcessArgs) *NullableClusterDescriptionProcessArgs {
	return &NullableClusterDescriptionProcessArgs{value: val, isSet: true}
}

func (v NullableClusterDescriptionProcessArgs) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableClusterDescriptionProcessArgs) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


