/*
API version: 2.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package mongodbatlasv2

import (
	"encoding/json"
)

// checks if the ServerlessInstanceDescriptionConnectionStrings type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ServerlessInstanceDescriptionConnectionStrings{}

// ServerlessInstanceDescriptionConnectionStrings Collection of Uniform Resource Locators that point to the MongoDB database.
type ServerlessInstanceDescriptionConnectionStrings struct {
	// List of private endpoint-aware connection strings that you can use to connect to this serverless instance through a private endpoint. This parameter returns only if you created a private endpoint for this serverless instance and it is AVAILABLE.
	PrivateEndpoint []ServerlessInstanceDescriptionConnectionStringsPrivateEndpoint `json:"privateEndpoint,omitempty"`
	// Public connection string that you can use to connect to this serverless instance. This connection string uses the `mongodb+srv://` protocol.
	StandardSrv *string `json:"standardSrv,omitempty"`
}

// NewServerlessInstanceDescriptionConnectionStrings instantiates a new ServerlessInstanceDescriptionConnectionStrings object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewServerlessInstanceDescriptionConnectionStrings() *ServerlessInstanceDescriptionConnectionStrings {
	this := ServerlessInstanceDescriptionConnectionStrings{}
	return &this
}

// NewServerlessInstanceDescriptionConnectionStringsWithDefaults instantiates a new ServerlessInstanceDescriptionConnectionStrings object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewServerlessInstanceDescriptionConnectionStringsWithDefaults() *ServerlessInstanceDescriptionConnectionStrings {
	this := ServerlessInstanceDescriptionConnectionStrings{}
	return &this
}

// GetPrivateEndpoint returns the PrivateEndpoint field value if set, zero value otherwise.
func (o *ServerlessInstanceDescriptionConnectionStrings) GetPrivateEndpoint() []ServerlessInstanceDescriptionConnectionStringsPrivateEndpoint {
	if o == nil || IsNil(o.PrivateEndpoint) {
		var ret []ServerlessInstanceDescriptionConnectionStringsPrivateEndpoint
		return ret
	}
	return o.PrivateEndpoint
}

// GetPrivateEndpointOk returns a tuple with the PrivateEndpoint field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ServerlessInstanceDescriptionConnectionStrings) GetPrivateEndpointOk() ([]ServerlessInstanceDescriptionConnectionStringsPrivateEndpoint, bool) {
	if o == nil || IsNil(o.PrivateEndpoint) {
		return nil, false
	}
	return o.PrivateEndpoint, true
}

// HasPrivateEndpoint returns a boolean if a field has been set.
func (o *ServerlessInstanceDescriptionConnectionStrings) HasPrivateEndpoint() bool {
	if o != nil && !IsNil(o.PrivateEndpoint) {
		return true
	}

	return false
}

// SetPrivateEndpoint gets a reference to the given []ServerlessInstanceDescriptionConnectionStringsPrivateEndpoint and assigns it to the PrivateEndpoint field.
func (o *ServerlessInstanceDescriptionConnectionStrings) SetPrivateEndpoint(v []ServerlessInstanceDescriptionConnectionStringsPrivateEndpoint) {
	o.PrivateEndpoint = v
}

// GetStandardSrv returns the StandardSrv field value if set, zero value otherwise.
func (o *ServerlessInstanceDescriptionConnectionStrings) GetStandardSrv() string {
	if o == nil || IsNil(o.StandardSrv) {
		var ret string
		return ret
	}
	return *o.StandardSrv
}

// GetStandardSrvOk returns a tuple with the StandardSrv field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ServerlessInstanceDescriptionConnectionStrings) GetStandardSrvOk() (*string, bool) {
	if o == nil || IsNil(o.StandardSrv) {
		return nil, false
	}
	return o.StandardSrv, true
}

// HasStandardSrv returns a boolean if a field has been set.
func (o *ServerlessInstanceDescriptionConnectionStrings) HasStandardSrv() bool {
	if o != nil && !IsNil(o.StandardSrv) {
		return true
	}

	return false
}

// SetStandardSrv gets a reference to the given string and assigns it to the StandardSrv field.
func (o *ServerlessInstanceDescriptionConnectionStrings) SetStandardSrv(v string) {
	o.StandardSrv = &v
}

func (o ServerlessInstanceDescriptionConnectionStrings) MarshalJSONWithoutReadOnly() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}
func (o ServerlessInstanceDescriptionConnectionStrings) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	return toSerialize, nil
}

type NullableServerlessInstanceDescriptionConnectionStrings struct {
	value *ServerlessInstanceDescriptionConnectionStrings
	isSet bool
}

func (v NullableServerlessInstanceDescriptionConnectionStrings) Get() *ServerlessInstanceDescriptionConnectionStrings {
	return v.value
}

func (v *NullableServerlessInstanceDescriptionConnectionStrings) Set(val *ServerlessInstanceDescriptionConnectionStrings) {
	v.value = val
	v.isSet = true
}

func (v NullableServerlessInstanceDescriptionConnectionStrings) IsSet() bool {
	return v.isSet
}

func (v *NullableServerlessInstanceDescriptionConnectionStrings) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableServerlessInstanceDescriptionConnectionStrings(val *ServerlessInstanceDescriptionConnectionStrings) *NullableServerlessInstanceDescriptionConnectionStrings {
	return &NullableServerlessInstanceDescriptionConnectionStrings{value: val, isSet: true}
}

func (v NullableServerlessInstanceDescriptionConnectionStrings) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableServerlessInstanceDescriptionConnectionStrings) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


