## Note this workflow is replicated to the master branch
## When editing please consider updating master branch with the same changes.
name: Generate Client
on:
 push:
  branches:
    - sdkv2

jobs:
  generate-client:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v3
        with:
          go-version: 1.19
      - name: Checkout
        uses: actions/checkout@v3
      - name: Fetch changes
        working-directory: ./tools
        run: make fetch_openapi
      - name: Verify Changed files
        uses: tj-actions/verify-changed-files@v13
        id: verify-changed-files
        with:
          files: |
             **/atlas-api.yaml
      - name: Run generation
        if: steps.verify-changed-files.outputs.files_changed == 'true'
        working-directory: ./tools
        run: make clean_and_generate
      - uses: peter-evans/create-pull-request@v4
        if: steps.verify-changed-files.outputs.files_changed == 'true'
        with:
          title: "OpenAPI client update based on OpenAPI file"
          commit-message: "openapi client update"
          delete-branch: true
          base: sdkv2
          branch: autogenerated-client
          body: |
            Automatic update for MongoDB Atlas Go Client based on OpenAPI changes.
            PR contains autogenerated changes for the MongoDB Atlas client.
            
            ## Review procedure
            
            1. Review changes in the OpenAPI file
            2. Check for new versions in versions.yaml file
            3. Review go client changes 
            

            
