name: OpenAPI Tools build
on:
  pull_request:
    paths:
      - "tools/**"

jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - working-directory: ./tools
        run: |
          npm install
          npm ci
